/**
 * build-config.js
 * Runs during Netlify build (via netlify.toml command).
 * Reads TMDB_API_KEY from Netlify environment variables and
 * writes js/config.js so the browser can use TMDb live data.
 *
 * This way the API key is NEVER stored in Git — it lives
 * only in Netlify's environment variable settings.
 */

const fs   = require('fs');
const path = require('path');

const key = process.env.TMDB_API_KEY || '';

if (!key) {
  console.warn('⚠️  WARNING: TMDB_API_KEY env var is not set.');
  console.warn('   The site will fall back to static data.');
}

const content = `/* ============================================================
   config.js — Auto-generated by build-config.js at deploy time.
   DO NOT edit manually. Set TMDB_API_KEY in Netlify env vars.
   ============================================================ */

const TMDB_CONFIG = {
  API_KEY: '${key}',
  BASE_URL: 'https://api.themoviedb.org/3',
  IMAGE_BASE_URL: 'https://image.tmdb.org/t/p',

  IMG: {
    POSTER_SM:   'https://image.tmdb.org/t/p/w185',
    POSTER_MD:   'https://image.tmdb.org/t/p/w342',
    POSTER_LG:   'https://image.tmdb.org/t/p/w500',
    BACKDROP_MD: 'https://image.tmdb.org/t/p/w780',
    BACKDROP_LG: 'https://image.tmdb.org/t/p/w1280',
    PROFILE:     'https://image.tmdb.org/t/p/w185',
  },

  FALLBACK_POSTER:   'assets/no-image.jpg',
  FALLBACK_BACKDROP: 'assets/no-backdrop.jpg',
};
`;

const outPath = path.join(__dirname, 'js', 'config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('✅ js/config.js written with TMDB_API_KEY from environment.');
